site_name: 樹海クラウド会計支援サービス マニュアル
site_description: ユーザー向け運用マニュアル
docs_dir: docs
theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - navigation.instant
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
extra:
  robots: noindex
plugins:
  - search
  - tags
nav:
  - ホーム: index.md
  - はじめに: getting-started.md
  - タグ一覧: tags.md
  - ログイン: login.md
  - 基本操作（工事中）:
      - 工事中: index.md
  - 各種設定: 
      - システム設定: masters/system_setting.md
      - 部門設定: masters/division_setting.md
      - 管理者設定（ユーザー設定）: masters/user_setting.md
      - 文字認識設定: masters/ocr_setting.md
      - 勘定科目設定: masters/kamoku_setting.md
      - コードマスタ: masters/code_setting.md
      - 支払権限: masters/role_setting.md
      - 支払権限ユーザー: masters/role_user_setting.md
      - 会計処理: masters/process_setting.md
      - 支払い方法: masters/payment_setting.md
  - ヘルプ:
      - 導入時初期設定: masters/init_setting.md
