site_name: 樹海クラウド会計支援サービス マニュアル
site_description: ユーザー向け運用マニュアル
docs_dir: docs
theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - navigation.instant
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
extra:
  robots: noindex
plugins:
  - search
  - tags
nav:
  - ホーム: index.md
  - はじめに: getting-started.md
  - タグ一覧: tags.md
  - ログイン: login.md
  - トップ（ダッシュボード）: home.md
  - 基本操作:
      - 支払伺い作成（書類取込）: operations/document_entry.md
      - 支払承認／確認: operations/document_approval.md
  - 経理業務:
      - 口座振替FD作成: operations/bank_fd.md
      - 仕訳確定: operations/accounting_approval.md
      - 仕訳データ（CSV）作成: operations/output_csv.md
  - 各種設定: 
      - システム設定: masters/system_setting.md
      - 部門設定: masters/division_setting.md
      - 管理者設定（ユーザー設定）: masters/user_setting.md
      - 文字認識設定: masters/ocr_setting.md
      - 勘定科目設定: masters/kamoku_setting.md
      - コードマスタ: masters/code_setting.md
      - 支払権限: masters/role_setting.md
      - 支払権限ユーザー: masters/role_user_setting.md
      - 会計処理: masters/process_setting.md
      - 支払い方法: masters/payment_setting.md
  - FAQ: faq.md
  - ヘルプ:
      - 導入時初期設定: masters/init_setting.md
